-- ==========================================
-- 1. Create Profiles Table
-- Stores extra user info (Name, Address, Phone)
-- Linked to auth.users via ID
-- ==========================================
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  address text,
  phone text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- ==========================================
-- 2. Create Bill History Table
-- Stores the calculation results
-- ==========================================
create table public.bill_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  month text not null,
  kwh numeric not null,
  rate numeric not null,
  total_amount numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- 3. Enable Row Level Security (RLS)
-- This ensures users can ONLY access their own data
-- ==========================================
alter table public.profiles enable row level security;
alter table public.bill_history enable row level security;

-- ==========================================
-- 4. Create Security Policies for Profiles
-- ==========================================

-- Allow users to view their own profile
create policy "Users can view own profile" 
on public.profiles for select 
using (auth.uid() = id);

-- Allow users to update their own profile
create policy "Users can update own profile" 
on public.profiles for update 
using (auth.uid() = id);

-- Allow users to insert their own profile (used during upsert/registration)
create policy "Users can insert own profile" 
on public.profiles for insert 
with check (auth.uid() = id);

-- ==========================================
-- 5. Create Security Policies for Bill History
-- ==========================================

-- Allow users to view their own history
create policy "Users can view own history" 
on public.bill_history for select 
using (auth.uid() = user_id);

-- Allow users to insert new calculations
create policy "Users can insert own history" 
on public.bill_history for insert 
with check (auth.uid() = user_id);

-- Allow users to delete their own records
create policy "Users can delete own history" 
on public.bill_history for delete 
using (auth.uid() = user_id);

-- ==========================================
-- 6. Auto-Create Profile Trigger (Optional but Recommended)
-- Automatically creates a row in 'profiles' when a user signs up
-- ==========================================
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();